version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=irrigation
    ports:
      - '5432:5432'
  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - 9411:9411
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_PARTITIONS_PER_TOPIC=3